# Chocolatey install script for go-package-yourself
# Generated by gpy Chocolatey generator

$ErrorActionPreference = 'Stop'
$toolsDir = "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)"

# Detect Windows architecture
$archMap = @{
    'AMD64' = @{ arch = 'x64'; gpy_arch = 'amd64' }
    'x86' = @{ arch = 'x86'; gpy_arch = 'amd64' }
    'ARM64' = @{ arch = 'arm64'; gpy_arch = 'arm64' }
}

$procArch = $env:PROCESSOR_ARCHITECTURE
if (-not $archMap.ContainsKey($procArch)) {
    throw "Unsupported architecture: $procArch. Supported: AMD64, ARM64"
}

$archInfo = $archMap[$procArch]
$localArch = $archInfo.gpy_arch

# Map architecture to download URLs and checksums
$downloadMap = @{
    'amd64' = @{
        url = 'https://github.com/Tillman32/go-package-yourself/releases/download/0.0.0/go-package-yourself__windows_amd64.zip'
        checksum = 'dd25e589db081ede6dbfff3b3db0cac84c5ad1aad0ad72156d30289ab1fc89a6'
        archive = 'go-package-yourself__windows_amd64.zip'
    }
}

if (-not $downloadMap.ContainsKey($localArch)) {
    throw "No binary available for architecture: $localArch"
}

$info = $downloadMap[$localArch]
$downloadUrl = $info.url
$expectedChecksum = $info.checksum
$archiveName = $info.archive

# Download archive from GitHub Release
$downloadPath = Join-Path $env:TEMP $archiveName
Write-Host "Downloading from: $downloadUrl"
try {
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath
} catch {
    throw "Failed to download package: $_"
}

# Verify SHA256 checksum
Write-Host "Verifying checksum..."
try {
    $hasher = [System.Security.Cryptography.HashAlgorithm]::Create('sha256')
    $fileStream = [System.IO.File]::OpenRead($downloadPath)
    $hashBytes = $hasher.ComputeHash($fileStream)
    $fileStream.Close()
    $actualChecksum = [System.BitConverter]::ToString($hashBytes) -replace '-',''
    $actualChecksum = $actualChecksum.ToLower()

    if ($actualChecksum -ne $expectedChecksum.ToLower()) {
        throw "Checksum mismatch!\nExpected: $expectedChecksum\nActual: $actualChecksum"
    }
    Write-Host "Checksum verified successfully"
} catch {
    Remove-Item -Path $downloadPath -Force -ErrorAction SilentlyContinue
    throw "Checksum verification failed: $_"
}

# Extract archive
Write-Host "Extracting archive..."
try {
    Expand-Archive -Path $downloadPath -DestinationPath $toolsDir -Force
    Write-Host "Extraction complete"
} catch {
    Remove-Item -Path $downloadPath -Force -ErrorAction SilentlyContinue
    throw "Failed to extract archive: $_"
}

# Cleanup downloaded archive
Remove-Item -Path $downloadPath -Force -ErrorAction SilentlyContinue
Write-Host "Installation complete"
