# Chocolatey uninstall script for go-package-yourself
# Generated by gpy Chocolatey generator

$ErrorActionPreference = 'Stop'

# Uninstall removes the binary from the tools directory
# This is typically handled by Chocolatey automatically,
# but this script can perform additional cleanup if needed.

try {
    Write-Host "go-package-yourself is being uninstalled"
} catch {
    Write-Warning "Uninstall error: $_"
}
