// Package docker implements the Dockerfile generator for go-package-yourself.
// It generates a production-quality multi-stage Dockerfile and .dockerignore
// at the project root, suitable for containerizing any Go CLI tool.
package docker

import (
	"fmt"
	"sort"
	"strings"

	"go-package-yourself/internal/generator"
	"go-package-yourself/internal/templatex"
)

// Generator implements the docker artifact generator.
// Implements the generator.Generator interface.
type Generator struct{}

// Name returns the canonical name of this generator.
func (g *Generator) Name() string {
	return "docker"
}

// Generate produces the Dockerfile and .dockerignore files at the project root.
// Returns nil, nil if docker is not enabled in the config.
func (g *Generator) Generate(ctx generator.Context) ([]generator.FileOutput, error) {
	if !ctx.Config.Packages.Docker.Enabled {
		return nil, nil
	}

	cfg := ctx.Config
	dockerCfg := cfg.Packages.Docker

	// Render CMD template (supports {{name}} placeholder)
	renderer := &templatex.Renderer{
		Data: map[string]string{
			"name": cfg.Project.Name,
		},
	}
	cmd, err := renderer.RenderWithFieldPath(dockerCfg.Cmd, "packages.docker.cmd")
	if err != nil {
		return nil, fmt.Errorf("packages.docker.cmd: %w", err)
	}

	dockerfile := buildDockerfile(
		cfg.Project.Name,
		cfg.Go.Main,
		cfg.Go.CGO,
		cfg.Go.LDFlags,
		dockerCfg.Port,
		dockerCfg.Env,
		cmd,
	)

	dockerignore := buildDockerignore()

	return []generator.FileOutput{
		{
			Path:    "Dockerfile",
			Content: []byte(dockerfile),
			Mode:    0o644,
		},
		{
			Path:    ".dockerignore",
			Content: []byte(dockerignore),
			Mode:    0o644,
		},
	}, nil
}

// buildDockerfile constructs the Dockerfile content from config values.
func buildDockerfile(name, goMain string, cgo bool, ldflags string, port int, envVars map[string]string, cmd string) string {
	cgoEnabled := "0"
	if cgo {
		cgoEnabled = "1"
	}

	ldflagsStr := "-X main.version=${VERSION}"
	if ldflags != "" {
		ldflagsStr = ldflags + " " + ldflagsStr
	}

	var sb strings.Builder

	// Header
	sb.WriteString("# Generated by gpy (go-package-yourself) — DO NOT EDIT\n")
	sb.WriteString("# Regenerate with: gpy package --only docker\n\n")

	// Build stage
	sb.WriteString("# Build stage\n")
	sb.WriteString("FROM golang:1.23-alpine AS builder\n\n")
	sb.WriteString("ARG VERSION=dev\n\n")
	sb.WriteString("RUN apk add --no-cache git\n\n")
	sb.WriteString("WORKDIR /app\n\n")
	sb.WriteString("COPY go.mod go.sum ./\n")
	sb.WriteString("RUN go mod download\n\n")
	sb.WriteString("COPY . .\n\n")
	fmt.Fprintf(&sb, "RUN CGO_ENABLED=%s go build -ldflags \"%s\" -trimpath -o %s %s\n\n", cgoEnabled, ldflagsStr, name, goMain)

	// Runtime stage
	sb.WriteString("# Runtime stage\n")
	sb.WriteString("FROM alpine:latest\n\n")
	sb.WriteString("RUN apk --no-cache add ca-certificates\n\n")
	sb.WriteString("RUN addgroup -g 1000 appuser && \\\n")
	sb.WriteString("    adduser -D -u 1000 -G appuser appuser\n\n")
	sb.WriteString("WORKDIR /app\n\n")
	fmt.Fprintf(&sb, "COPY --from=builder /app/%s .\n", name)
	fmt.Fprintf(&sb, "RUN chown appuser:appuser %s\n\n", name)
	sb.WriteString("USER appuser\n")

	// ENV directives (sorted for determinism)
	if len(envVars) > 0 {
		sb.WriteString("\n")
		keys := make([]string, 0, len(envVars))
		for k := range envVars {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&sb, "ENV %s=%s\n", k, envVars[k])
		}
	}

	// EXPOSE
	if port > 0 {
		sb.WriteString("\n")
		fmt.Fprintf(&sb, "EXPOSE %d\n", port)
	}

	// CMD
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "CMD [\"%s\"]\n", cmd)

	return sb.String()
}

// buildDockerignore returns the .dockerignore content.
func buildDockerignore() string {
	return `.git
packaging
*.exe
*.test
dist
vendor
`
}

// New creates a new Docker Generator instance.
func New() generator.Generator {
	return &Generator{}
}
